spring.application.name=transfer-service

# Conexão com o Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/transfer
spring.datasource.username=transfer
spring.datasource.password=transfer

# Flyway controla o schema; Hibernate só valida
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true