spring.application.name=transfer-service

# Conexão com o Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/transfer
spring.datasource.username=transfer
spring.datasource.password=transfer

# Flyway controla o schema; Hibernate só valida
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Mongo
spring.data.mongodb.uri=mongodb://localhost:27017/transfer
spring.data.mongodb.database=transfer
spring.data.mongodb.uuid-representation=standard